# FROM node:20-alpine

# WORKDIR /app

# COPY . .

# RUN npm i -g pnpm

# # install workspace
# RUN pnpm install --frozen-lockfile

# # build using node_modules binary directly (bypass pnpm resolution issues)
# WORKDIR /app/apps/api
# RUN ../../node_modules/.bin/next build

# EXPOSE 3000

# CMD ["../../node_modules/.bin/next", "start"]
